---
- name: general stuff to install
  hosts: all
  remote_user: sudo
  become: true

  tasks:
    - name: get update
      apt:
        upgrade: yes
        update_cache: yes

- name: stuff for app
  hosts: app
  remote_user: sudo
  become: yes

  vars:
    ansible_distribution_release: "xenial"

  tasks:
    - name: install git
      apt:
        name: git
        state: present
        update_cache: yes

    - name: Install the gpg key for nodejs LTS
      apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      apt_repository:
        repo: "deb https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main"
        state: present

    - name: Install the nodejs
      apt:
        name: nodejs

    - name: install pm2
      npm:
        name: pm2
        global: yes

    - name: install nginx
      apt:
        name: nginx

    - name: adding variable
      shell: echo "export DB_HOST=mongodb://192.168.10.150:27017/posts" >> /home/vagrant/.bashrc



- name: stuff for the database
  hosts: db
  remote_user: sudo
  become: true

  tasks:
    - name: mongo install key
      apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present

    - name: MongoDB - Add repository
      apt_repository:
        filename: '/etc/apt/sources.list.d/mongodb-org-4.2.list'
        repo: 'deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse'
        state: present
        update_cache: yes

    - name: MongoDB - Install MongoDB
      apt:
        name: mongodb-org
        state: present
        update_cache: yes

    - name: changing the config on db
      shell: rm /etc/mongod.conf; ln -s /home/ubuntu/environment/db/mongod.conf /etc/mongod.conf; systemctl restart mongod; systemctl enable mongod
